// Firebase core package — required to initialize the Firebase SDK
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
// Provides platform-specific Firebase configuration generated by
// the FlutterFire CLI (see lib/firebase_options.dart)
import 'package:study_planner/firebase_options.dart';
import 'package:study_planner/routes/router_class.dart';

void main() async {
  // Ensure Flutter bindings are initialized before calling platform code.
  // This is required when you perform asynchronous work in `main()`
  // before `runApp()` (e.g., initializing Firebase).
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the options that match the current platform.
  // `DefaultFirebaseOptions.currentPlatform` is defined in
  // `lib/firebase_options.dart` and is generated by the FlutterFire CLI.
  // If Firebase fails to initialize, inspect the error message — common
  // issues include incorrect configuration values or missing platform
  // setup in the Firebase console.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      routerConfig: RouterClass().router,
      theme: ThemeData(
        fontFamily: GoogleFonts.poppins().fontFamily,
        brightness: Brightness.dark,
      ),
    );
  }
}
